---
# tasks file for testtemplates
#
- name: copy templates
  template:
    src: templates/{{ item.templatefilename }}
    dest: /home/deploy/test_templates

  with_items: 
    - "{{ templatefile }}"
