---

- name: configure httpd 
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: 
   - restart apache service

- name: send index.html
  copy: src=index.html dest=/var/www/html/index.html
